
services:
  database:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: pay_flex
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  api:
    build: .
    container_name: minha-api
    depends_on:
      - database
    environment:
      DB_HOST: meu-mysql
      DB_USER: root
      DB_PASSWORD: "123456"
      DB_NAME: pay_flex
      DB_PORT: 3306
    ports:
      - "3000:3000"
    command: ["npx", "ts-node", "src/app.ts"]

volumes:
  db_data:
